services:
  - docker

env:
  global:
  - VERSION_PORTAIL=1.3.10
  - VERSION_ODFE=1.7.0
  - VERSION_SENTINL=v7.6.1-b5
  - VERSION_LEADWIRE=1.0.0
  
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u leadwire --password-stdin
      - docker build -t leadwire/apm-leadwire-portail -build-arg VERSION_PORTAIL=$VERSION_PORTAIL  -f Dockerfile-leadwire-portail . 
      - docker tag apm-leadwire-portail leadwire/apm-leadwire-portail:$VERSION_LEADWIRE
      - docker push leadwire/apm-leadwire-portail:$VERSION_LEADWIRE
      - docker build -t leadwire/apm-leadwire-socket.io -build-arg VERSION_PORTAIL=$VERSION_PORTAIL  -f Dockerfile-leadwire-socket.io . 
      - docker tag apm-leadwire-socket.io leadwire/apm-leadwire-socket.io:$VERSION_LEADWIRE
      - docker push leadwire/apm-leadwire-socket.io:$VERSION_LEADWIRE
      - docker build -t leadwire/apm-leadwire-kibana -build-arg VERSION_ODFE=$VERSION_ODFE -build-arg VERSION_SENTINL=$VERSION_SENTINL -f Dockerfile-leadwire-kibana . 
      - docker tag apm-leadwire-kibana leadwire/apm-leadwire-kibana:$VERSION_LEADWIRE
      - docker push leadwire/apm-leadwire-kibana:$VERSION_LEADWIRE
      - docker build -t leadwire/apm-leadwire-core -f Dockerfile-leadwire-core . 
      - docker tag apm-leadwire-core leadwire/apm-leadwire-core:$VERSION_LEADWIRE
      - docker push leadwire/apm-leadwire-core:$VERSION_LEADWIRE
      - docker build -t leadwire/apm-leadwire-ldap -f Dockerfile-leadwire-ldap . 
      - docker tag apm-leadwire-ldap leadwire/apm-leadwire-ldap:$VERSION_LEADWIRE
      - docker push leadwire/apm-leadwire-ldap:$VERSION_LEADWIRE
