services:
  - docker

env:
  global:
  - VERSION_PORTAIL=1.3.19
  - VERSION_LEADWIRE=1.0.10
  - VERSION_LEADWIRE_UI=1.0.8
  - DOCKER_REGISTRY_URL=hub.docker.com
  - DOCKER_PASSWORD=${DOCKER_PASSWORD}
  - GIT_TOKEN=${GIT_TOKEN}
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u "leadwire" -p $DOCKER_PASSWORD 
      - docker build -t leadwire/apm-leadwire-portail-ui --build-arg BRANCH=master --build-arg GIT_TOKEN=${GIT_TOKEN} --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -f Dockerfile-leadwire-ui . 
      - docker tag leadwire/apm-leadwire-portail-ui leadwire/apm-leadwire-portail-ui:${VERSION_LEADWIRE_UI}
      - docker push leadwire/apm-leadwire-portail-ui:${VERSION_LEADWIRE_UI}
      - docker build -t leadwire/apm-leadwire-portail --build-arg VERSION_PORTAIL=${VERSION_PORTAIL} --build-arg BRANCH=development --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -f Dockerfile-leadwire-portail . 
      - docker tag leadwire/apm-leadwire-portail leadwire/apm-leadwire-portail:${VERSION_LEADWIRE}
      - docker push leadwire/apm-leadwire-portail:${VERSION_LEADWIRE}
#      - docker build -t leadwire/apm-leadwire-socket.io --build-arg VERSION_PORTAIL=${VERSION_PORTAIL} --build-arg GIT_TOKEN=${GIT_TOKEN} --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -f Dockerfile-leadwire-socket.io . 
#      - docker tag leadwire/apm-leadwire-socket.io leadwire/apm-leadwire-socket.io:${VERSION_LEADWIRE}
#      - docker push leadwire/apm-leadwire-socket.io:${VERSION_LEADWIRE}
#      - docker build -t leadwire/apm-leadwire-core --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')  -f Dockerfile-leadwire-core . 
#      - docker tag leadwire/apm-leadwire-core leadwire/apm-leadwire-core:${VERSION_LEADWIRE}
#      - docker push leadwire/apm-leadwire-core:${VERSION_LEADWIRE}
#      - docker build -t leadwire/apm-leadwire-ldap --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')  -f Dockerfile-leadwire-ldap . 
#      - docker tag leadwire/apm-leadwire-ldap leadwire/apm-leadwire-ldap:${VERSION_LEADWIRE}
#      - docker push leadwire/apm-leadwire-ldap:${VERSION_LEADWIRE}
